### ISSUE TITLE
Godot editor crashes 

### ISSUE THREAD

**Issue by jacobabarbary** [don-tnowe/godot-inspector-extender#1]
When I try to instance a tscn with this script attached the editor crashes.

**Comment by don-tnowe** [comment]
Why do you

You're not supposed to use classes from this addon inside your project files, you just add a bunch of comments and it only changes things while you're viewing from the editor

**Comment by don-tnowe** [comment]
There is too much information missing here, so I'm just closing this. Feel free to add anything that will let me actually fix the issue

**Comment by jacobabarbary** [comment]
Hey, sorry I didn't give enough information, I'm really not sure what information you need though.

**Comment by jacobabarbary** [comment]
(I had a tool script with the comments in it that was crashing my editor)

**Comment by don-tnowe** [comment]
What did you do before it happened? What did the script contain? What does the scene contain? What errors appered in the console (*if any*)? Does it happen when you activate the plugin **after** you add the node?

Can you make a copy of your scenes and gradually remove elements until the crash does not happen, then send a project with just the scenes/script in the last state where the crash **did** happen? A minimal reproduction project, that is?
