### ISSUE TITLE
[Question] Does this be designed to use together with godot-dictionary-inspector?

### ISSUE THREAD

**Issue by JustusPan** [don-tnowe/godot-inspector-extender#4]
https://github.com/don-tnowe/godot-dictionary-inspector
are they compatible with each other?

**Comment by don-tnowe** [comment]
Well, Inspector Extender's tables don't allow editing of nested Dictionary and Array properties, and dictionaries don't allow attributes on specific properties so Dictionary Inspector doesn't need to handle them.

What are the interactions you are looking for?
